"""Extract the LAWS-resolution rows from the official UN GA voting dataset.

Pipeline: Walker-supplied official CSV (never fetched by tooling, never
committed) -> committed extract with provenance header
(data/source/ga_voting_extract.csv.gz) -> derived per-state trajectories
(data/derived/votes.json.gz), keyed by ISO 3166-1 alpha-3.

The extractor refuses to write anything if the source rows fail the
reconciliation checks recorded in Phase 0: exactly 193 rows per resolution,
vote counts matching both the expected plenary tallies and the totals
embedded in the dataset itself.
"""

import csv
import gzip
import io
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from config import config

TARGET_RESOLUTIONS = {f"A/RES/{key}": key for key in config.LAWS_RESOLUTIONS}

EXTRACT_COLUMNS = [
    "undl_id", "ms_code", "ms_name", "ms_vote", "date", "session",
    "resolution", "draft", "meeting", "title",
    "total_yes", "total_no", "total_abstentions", "total_non_voting",
    "total_ms", "undl_link",
]

PROVENANCE_HEADER = """\
# Machine Politics: extract of the three UN GA resolutions on lethal
# autonomous weapons systems (78/241, 79/62, 80/57), 193 rows each.
# Source: United Nations Dag Hammarskjold Library, General Assembly Voting
# Data, version 5 (February 2026), {record_url}
# (c) United Nations, 2026, https://digitallibrary.un.org,
# downloaded on {downloaded_on}. Non-commercial use, with attribution.
# See DATA_LICENSE.md at the repository root. Generated by
# tools/votes_extract.py; comment lines start with '#'.
"""


class ExtractionError(Exception):
    """Raised when the source data fails a reconciliation check."""


def find_source_csv():
    candidates = sorted(config.SCRATCH_SOURCE_DIR.glob("*_ga_voting.csv"))
    if not candidates:
        raise ExtractionError(
            f"no *_ga_voting.csv in {config.SCRATCH_SOURCE_DIR}; "
            "the dataset enters only by manual analyst download "
            "(see DATA_LICENSE.md)"
        )
    return candidates[-1]


def read_laws_rows(source_csv):
    rows_by_res = {key: [] for key in config.LAWS_RESOLUTIONS}
    with open(source_csv, encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            key = TARGET_RESOLUTIONS.get(row["resolution"])
            if key is not None:
                rows_by_res[key].append(row)
    return rows_by_res


def reconcile(rows_by_res):
    """Fail loudly unless every resolution reconciles with known truth."""
    for key, spec in config.LAWS_RESOLUTIONS.items():
        rows = rows_by_res[key]
        if len(rows) != 193:
            raise ExtractionError(f"{key}: expected 193 rows, found {len(rows)}")
        codes = [r["ms_code"] for r in rows]
        if len(set(codes)) != 193:
            raise ExtractionError(f"{key}: duplicate ms_code in rows")
        counts = {v: 0 for v in config.VOTE_VALUES}
        for r in rows:
            if r["ms_vote"] not in config.VOTE_VALUES:
                raise ExtractionError(
                    f"{key}: unexpected vote value {r['ms_vote']!r} "
                    f"for {r['ms_code']}"
                )
            counts[r["ms_vote"]] += 1
        got = (counts["Y"], counts["N"], counts["A"])
        if got != spec["tally"]:
            raise ExtractionError(
                f"{key}: tally {got} does not match expected {spec['tally']}"
            )
        embedded = (
            int(float(rows[0]["total_yes"])),
            int(float(rows[0]["total_no"])),
            int(float(rows[0]["total_abstentions"])),
        )
        if embedded != spec["tally"]:
            raise ExtractionError(
                f"{key}: embedded totals {embedded} disagree with "
                f"expected {spec['tally']}"
            )


def write_extract(rows_by_res, out_path):
    buf = io.StringIO()
    buf.write(
        PROVENANCE_HEADER.format(
            record_url=config.UN_DATASET_RECORD_URL,
            downloaded_on=config.UN_DATASET_DOWNLOADED_ON,
        )
    )
    writer = csv.DictWriter(buf, fieldnames=EXTRACT_COLUMNS, extrasaction="ignore")
    writer.writeheader()
    for key in config.LAWS_RESOLUTIONS:
        for row in sorted(rows_by_res[key], key=lambda r: r["ms_code"]):
            writer.writerow(row)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    _write_gz_deterministic(out_path, buf.getvalue().encode("utf-8"))


def read_extract(path):
    """Read the committed extract back, skipping provenance comment lines."""
    with gzip.open(path, "rt", encoding="utf-8", newline="") as f:
        lines = [ln for ln in f if not ln.startswith("#")]
    return list(csv.DictReader(lines))


def build_derived(rows_by_res):
    resolutions = {}
    states = {}
    for key, spec in config.LAWS_RESOLUTIONS.items():
        first = rows_by_res[key][0]
        resolutions[key] = {
            "symbol": f"A/RES/{key}",
            "date": first["date"],
            "session": first["session"],
            "title": first["title"],
            "tally": {
                "yes": spec["tally"][0],
                "no": spec["tally"][1],
                "abstain": spec["tally"][2],
            },
            "undl_link": first["undl_link"],
        }
        for row in rows_by_res[key]:
            state = states.setdefault(
                row["ms_code"], {"un_name": row["ms_name"], "votes": {}}
            )
            state["votes"][key] = row["ms_vote"]
            state["un_name"] = row["ms_name"]  # most recent name wins
    return {
        "updated_through": config.UPDATED_THROUGH,
        "source": {
            "record_url": config.UN_DATASET_RECORD_URL,
            "downloaded_on": config.UN_DATASET_DOWNLOADED_ON,
            "attribution": "© United Nations, 2026, https://digitallibrary.un.org",
        },
        "resolutions": resolutions,
        "states": dict(sorted(states.items())),
    }


def check_derived(derived):
    """Both-direction guard, data side (invariant 8).

    Every state carries a vote for every resolution and every resolution's
    votes come only from states present in the state table. The site build
    extends this guard to pages in both directions.
    """
    state_codes = set(derived["states"])
    if len(state_codes) != 193:
        raise ExtractionError(f"expected 193 states, found {len(state_codes)}")
    for code, entry in derived["states"].items():
        missing = set(config.LAWS_RESOLUTIONS) - set(entry["votes"])
        if missing:
            raise ExtractionError(f"{code}: missing votes for {sorted(missing)}")
        for res, vote in entry["votes"].items():
            if vote not in config.VOTE_VALUES:
                raise ExtractionError(f"{code}/{res}: bad vote {vote!r}")


def _write_gz_deterministic(path, payload):
    with open(path, "wb") as raw:
        # filename="" and mtime=0 keep the byte stream identical across
        # rebuilds so the committed artifacts never churn without cause
        with gzip.GzipFile(filename="", fileobj=raw, mode="wb", mtime=0) as gz:
            gz.write(payload)


def write_derived(derived, out_path):
    out_path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(derived, ensure_ascii=False, indent=1).encode("utf-8")
    _write_gz_deterministic(out_path, payload)


def main():
    source = find_source_csv()
    print(f"source: {source}")
    rows_by_res = read_laws_rows(source)
    reconcile(rows_by_res)
    write_extract(rows_by_res, config.VOTES_EXTRACT_CSV)
    print(f"wrote {config.VOTES_EXTRACT_CSV}")
    derived = build_derived(rows_by_res)
    check_derived(derived)
    write_derived(derived, config.VOTES_DERIVED_JSON)
    print(f"wrote {config.VOTES_DERIVED_JSON}")
    # round-trip: the committed extract alone must regenerate identical JSON
    rt_rows = {key: [] for key in config.LAWS_RESOLUTIONS}
    for row in read_extract(config.VOTES_EXTRACT_CSV):
        rt_rows[TARGET_RESOLUTIONS[row["resolution"]]].append(row)
    reconcile(rt_rows)
    if build_derived(rt_rows) != derived:
        raise ExtractionError("extract round-trip does not reproduce derived JSON")
    print("round-trip OK: extract regenerates identical derived JSON")


if __name__ == "__main__":
    main()
